services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./.docker-volumes/data:/data/db
      - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/
    env_file:
      - .env.local
